name: SonarQube Analysis
on:
  push:
    branches:
      - 'main'
      - 'feature/*'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libomp-dev
      - name: Set up vcpkg with cache
        uses: ./.github/actions/setup-vcpkg
        with:
          os: ubuntu-latest
      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v6
      - name: Run Build Wrapper
        run: |
          cmake --preset llvm-cov-debug
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build --preset llvm-cov-debug
      - name: Run tests to generate coverage information
        run: |
          LLVM_PROFILE_FILE="common.profraw" build/llvm-cov-debug/common/tests/common.tests
          LLVM_PROFILE_FILE="biofvm.profraw" build/llvm-cov-debug/reactions-diffusion/biofvm/tests/reactions-diffusion.biofvm.tests
          LLVM_PROFILE_FILE="micromechanics.profraw" build/llvm-cov-debug/mechanics/micromechanics/tests/mechanics.micromechanics.tests
          LLVM_PROFILE_FILE="physicell.profraw" build/llvm-cov-debug/mechanics/physicell/tests/physicore.mechanics.physicell.tests
          LLVM_PROFILE_FILE="biofvm.openmp_solver.profraw" build/llvm-cov-debug/reactions-diffusion/biofvm/kernels/openmp_solver/tests/reactions-diffusion.biofvm.kernels.openmp_solver.tests
          LLVM_PROFILE_FILE="biofvm.thrust_solver.profraw" build/llvm-cov-debug/reactions-diffusion/biofvm/kernels/thrust_solver/tests/reactions-diffusion.biofvm.kernels.tbb_thrust_solver.tests
      - name: Merge counters from different runs and convert the result into an llvm-cov-compatible form
        run: |
          llvm-profdata-18 merge -o merged.profdata common.profraw biofvm.profraw micromechanics.profraw physicell.profraw biofvm.openmp_solver.profraw biofvm.thrust_solver.profraw
      - name: Collect the coverage
        run: |
          llvm-cov-18 show --show-branches=count --instr-profile merged.profdata build/llvm-cov-debug/common/tests/common.tests -object build/llvm-cov-debug/reactions-diffusion/biofvm/tests/reactions-diffusion.biofvm.tests -object build/llvm-cov-debug/mechanics/micromechanics/tests/mechanics.micromechanics.tests -object build/llvm-cov-debug/reactions-diffusion/biofvm/kernels/openmp_solver/tests/reactions-diffusion.biofvm.kernels.openmp_solver.tests -object build/llvm-cov-debug/reactions-diffusion/biofvm/kernels/thrust_solver/tests/reactions-diffusion.biofvm.kernels.tbb_thrust_solver.tests -object build/llvm-cov-debug/mechanics/physicell/tests/physicore.mechanics.physicell.tests > coverage.txt
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.projectKey=bsc-life_PhysiCore
            --define sonar.organization=bsc-life
            --define sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json
            --define sonar.cfamily.llvm-cov.reportPath=coverage.txt
            --define sonar.sources=phenotype/physicore/src,common/include,reactions-diffusion/biofvm/src,reactions-diffusion/biofvm/include,mechanics/micromechanics/src,mechanics/micromechanics/include,mechanics/physicell/src,mechanics/physicell/include,reactions-diffusion/biofvm/kernels/openmp_solver/src,reactions-diffusion/biofvm/kernels/openmp_solver/examples,reactions-diffusion/biofvm/kernels/openmp_solver/include,reactions-diffusion/biofvm/kernels/thrust_solver/src,reactions-diffusion/biofvm/kernels/thrust_solver/examples,reactions-diffusion/biofvm/kernels/thrust_solver/include
            --define sonar.tests=common/tests,reactions-diffusion/biofvm/tests,mechanics/micromechanics/tests,mechanics/physicell/tests,reactions-diffusion/biofvm/kernels/openmp_solver/tests,reactions-diffusion/biofvm/kernels/thrust_solver/tests
            --define sonar.coverage.exclusions=reactions-diffusion/biofvm/kernels/openmp_solver/examples/*,reactions-diffusion/biofvm/kernels/thrust_solver/examples/*
            --define sonar.cpd.exclusions=reactions-diffusion/biofvm/kernels/openmp_solver/examples/*,reactions-diffusion/biofvm/kernels/thrust_solver/examples/*
